apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Копия https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/v0.12.0/deploy/standalone-install.yaml
# Вендорим, чтобы Argo CD не ходил на GitHub за манифестом.
resources:
  - standalone-install.yaml
