apiVersion: v2
name: cert-manager
description: cert-manager + ClusterIssuers Let's Encrypt (umbrella chart)
type: application
version: 0.1.0
dependencies:
  - name: cert-manager
    version: v1.21.1
    repository: http://10.10.0.5/helm/helm-jetstack
