apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: {{ .Values.image | quote }}
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: MEMORY_MAX_TRACES
              value: {{ .Values.maxTraces | quote }}
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: ui
              containerPort: 16686
          readinessProbe:
            httpGet:
              path: /
              port: ui
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
